# Generated by Django 6.1.1 on 2026-09-20 09:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(choices=[('r', 'red'), ('w', 'white'), ('rg', 'rosegold')], default='white', max_length=4),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2026, 9, 20, 13, 26, 56, 58362)),
        ),
    ]
