# Generated by Django 6.1.1 on 2026-09-23 04:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_order_date_alter_product_star'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='existance',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2026, 9, 23, 7, 38, 50, 164244)),
        ),
    ]
